---
title: Gold River Distillery
description: Gold River Distillery is the first legal distillery in Sacramento County since Prohibition.
meta_img: ./img/gr_logo_navbar.png
twitter: https://mobile.twitter.com/goldrdistillery
favicon: /img/GR_favicon.png
url: https://goldriverdistillery.com
prod-key: NTkzMjA1YzgtNjVkMy00YTEyLWFjZjItOTY5NGZiOGU1ODFhNjM3MzgxNzg2NzUyMzI1OTA2
dev-key: YjZjNjkyMTQtZDY3OC00ZjhmLWJiZTItMDU3NWQ5ZGRlODViNjM3MzgxNzg2NzUyMzI1OTA2
prod-url: https://goldriverdistillery.com  
gtm: GTM-KZ544XP
schema:
  name: Gold River Distillery
  phone: (916)476-3868
  location: 
    address: 11460 SUNRISE GOLD CIR. C
    city: RANCHO CORDOVA
    state: CA
    zip: 95742 
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
collections:
  terms:
    output: true
  pages: 
    output: true  
  products:
    output: true
 
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    type: products
  values:
    layout: product
    permalink: /product/:title
