---
title: Gold River Distillery
description: Gold River Distillery is the first legal distillery in Sacramento County since Prohibition.
meta_img: ./img/gr_logo_navbar.png
twitter: https://mobile.twitter.com/goldrdistillery
favicon:
url: https://goldriverdistillery.com/
gtm:
schema:
  name: Gold River Distillery
  type: 
  image: 
  logo:
  phone: (916)476-3868
  email: 
  social:
  location: 
    address: 11460 SUNRISE GOLD CIR. C
    city: RANCHO CORDOVA
    state: CA
    zip: 95742
  hours:
    days:
    opens:
    closes:  
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
collections:
  terms:
    output: true
  pages: 
    output: true  
  products:
    output: true
 
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    type: products
  values:
    layout: product
    permalink: /product/:title
