---
label: Product page
hide_body: false
fields:
- type: text
  name: title
  label: Product Title
- type: text
  name: price
  label: Price
  description: 'No currency. Just the price in dollars and cents: 22.00'
- type: file
  name: img
  label: Product image
  config:
    maxSize: 1
- name: list
  type: select
  default: []
  config:
    required: false
    options:
    - gin
    - 'applejack '
    - 'hand-sanitizer '
    - vodka
    - bourbon
    - absinthe
    - whiskey
    source:
      type: simple
      section: products
      file: 
      path: 
  label: Product type
pages:
- _products/vodka-1.md
