---
label: Product page
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: textarea
  name: content
  label: content
- type: text
  name: price
  label: price
- type: file
  name: img
  label: img
- type: file
  name: button-img
  label: button-img
- type: text
  name: button
  label: button
- type: text
  name: list
  label: list
